apiVersion: v1
kind: Service
metadata:
  name: microk8sdemo
spec:
  selector:
    app: microk8sdemo
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microk8sdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microk8sdemo
  template:
    metadata:
      labels:
        app: microk8sdemo
    spec:
      containers:
        - name: app
          image: localhost:32000/microk8sdemo:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
